-- Every tenant gets a versioned baseline dictionary. Tenant-specific policy changes create new rows rather than mutating these bootstrap IDs.
WITH stage_seed(key, label, terminal) AS (VALUES
  ('received','Received',0),
  ('source_identified','Source identified',0),
  ('assigned','Assigned',0),
  ('contact_attempted','Contact attempted',0),
  ('meaningful_connection','Meaningful connection',0),
  ('requirement_identified','Requirement identified',0),
  ('qualified','Qualified',0),
  ('follow_up_active','Follow-up active',0),
  ('appointment_suggested','Appointment suggested',0),
  ('appointment_booked','Appointment booked',0),
  ('appointment_confirmed','Appointment confirmed',0),
  ('arrived','Arrived',0),
  ('consultation','Consultation',0),
  ('treatment_advised','Treatment advised',0),
  ('financial_counseling','Financial counseling',0),
  ('procedure_booked','Procedure booked',0),
  ('admission','Admission',0),
  ('treatment_completed','Treatment completed',0),
  ('revenue_recorded','Revenue recorded',0),
  ('closed','Closed',1)
)
INSERT OR IGNORE INTO crm_lifecycle_stages (id, tenant_id, key, label, terminal, created_at, version)
SELECT t.id || ':stage:' || s.key, t.id, s.key, s.label, s.terminal, CAST(strftime('%s','now') AS integer) * 1000, 1 FROM crm_tenants t CROSS JOIN stage_seed s;--> statement-breakpoint
WITH transition_seed(from_key, to_key) AS (VALUES
  ('received','source_identified'),
  ('received','assigned'),
  ('received','closed'),
  ('source_identified','assigned'),
  ('source_identified','closed'),
  ('assigned','contact_attempted'),
  ('assigned','closed'),
  ('contact_attempted','contact_attempted'),
  ('contact_attempted','meaningful_connection'),
  ('contact_attempted','follow_up_active'),
  ('contact_attempted','closed'),
  ('meaningful_connection','requirement_identified'),
  ('meaningful_connection','follow_up_active'),
  ('meaningful_connection','closed'),
  ('requirement_identified','qualified'),
  ('requirement_identified','follow_up_active'),
  ('requirement_identified','closed'),
  ('qualified','follow_up_active'),
  ('qualified','appointment_suggested'),
  ('qualified','closed'),
  ('follow_up_active','contact_attempted'),
  ('follow_up_active','meaningful_connection'),
  ('follow_up_active','appointment_suggested'),
  ('follow_up_active','closed'),
  ('appointment_suggested','appointment_booked'),
  ('appointment_suggested','follow_up_active'),
  ('appointment_suggested','closed'),
  ('appointment_booked','appointment_confirmed'),
  ('appointment_booked','follow_up_active'),
  ('appointment_booked','closed'),
  ('appointment_confirmed','arrived'),
  ('appointment_confirmed','follow_up_active'),
  ('appointment_confirmed','closed'),
  ('arrived','consultation'),
  ('arrived','closed'),
  ('consultation','treatment_advised'),
  ('consultation','financial_counseling'),
  ('consultation','closed'),
  ('treatment_advised','financial_counseling'),
  ('treatment_advised','procedure_booked'),
  ('treatment_advised','treatment_completed'),
  ('treatment_advised','closed'),
  ('financial_counseling','procedure_booked'),
  ('financial_counseling','treatment_completed'),
  ('financial_counseling','closed'),
  ('procedure_booked','admission'),
  ('procedure_booked','treatment_completed'),
  ('procedure_booked','closed'),
  ('admission','treatment_completed'),
  ('admission','revenue_recorded'),
  ('admission','closed'),
  ('treatment_completed','revenue_recorded'),
  ('treatment_completed','closed'),
  ('revenue_recorded','closed')
)
INSERT OR IGNORE INTO crm_allowed_transitions (id, tenant_id, from_stage_id, to_stage_id, policy_json, created_at, version)
SELECT t.id || ':transition:' || e.from_key || ':' || e.to_key, t.id, t.id || ':stage:' || e.from_key, t.id || ':stage:' || e.to_key, '{"active":true,"bootstrap":true}', CAST(strftime('%s','now') AS integer) * 1000, 1 FROM crm_tenants t CROSS JOIN transition_seed e;--> statement-breakpoint
WITH reason_seed(key, label, requires_evidence) AS (VALUES
  ('not_interested','Not interested',1),
  ('unreachable','Unable to contact',0),
  ('invalid_contact','Invalid contact',1),
  ('clinically_ineligible','Clinically ineligible',1),
  ('financial','Financial constraint',1),
  ('competition','Competing provider',1),
  ('already_treated','Already treated',1),
  ('closed_other','Other documented reason',1)
)
INSERT OR IGNORE INTO crm_lifecycle_reasons (id, tenant_id, stage_id, key, label, requires_evidence, created_at, version)
SELECT t.id || ':reason:' || r.key, t.id, t.id || ':stage:closed', r.key, r.label, r.requires_evidence, CAST(strftime('%s','now') AS integer) * 1000, 1 FROM crm_tenants t CROSS JOIN reason_seed r;--> statement-breakpoint
CREATE TRIGGER `crm_tenant_lifecycle_bootstrap`
AFTER INSERT ON `crm_tenants`
FOR EACH ROW
BEGIN
  INSERT OR IGNORE INTO crm_lifecycle_stages (id, tenant_id, key, label, terminal, created_at, version) VALUES
    (NEW.id || ':stage:received', NEW.id, 'received', 'Received', 0, NEW.created_at, 1),
    (NEW.id || ':stage:source_identified', NEW.id, 'source_identified', 'Source identified', 0, NEW.created_at, 1),
    (NEW.id || ':stage:assigned', NEW.id, 'assigned', 'Assigned', 0, NEW.created_at, 1),
    (NEW.id || ':stage:contact_attempted', NEW.id, 'contact_attempted', 'Contact attempted', 0, NEW.created_at, 1),
    (NEW.id || ':stage:meaningful_connection', NEW.id, 'meaningful_connection', 'Meaningful connection', 0, NEW.created_at, 1),
    (NEW.id || ':stage:requirement_identified', NEW.id, 'requirement_identified', 'Requirement identified', 0, NEW.created_at, 1),
    (NEW.id || ':stage:qualified', NEW.id, 'qualified', 'Qualified', 0, NEW.created_at, 1),
    (NEW.id || ':stage:follow_up_active', NEW.id, 'follow_up_active', 'Follow-up active', 0, NEW.created_at, 1),
    (NEW.id || ':stage:appointment_suggested', NEW.id, 'appointment_suggested', 'Appointment suggested', 0, NEW.created_at, 1),
    (NEW.id || ':stage:appointment_booked', NEW.id, 'appointment_booked', 'Appointment booked', 0, NEW.created_at, 1),
    (NEW.id || ':stage:appointment_confirmed', NEW.id, 'appointment_confirmed', 'Appointment confirmed', 0, NEW.created_at, 1),
    (NEW.id || ':stage:arrived', NEW.id, 'arrived', 'Arrived', 0, NEW.created_at, 1),
    (NEW.id || ':stage:consultation', NEW.id, 'consultation', 'Consultation', 0, NEW.created_at, 1),
    (NEW.id || ':stage:treatment_advised', NEW.id, 'treatment_advised', 'Treatment advised', 0, NEW.created_at, 1),
    (NEW.id || ':stage:financial_counseling', NEW.id, 'financial_counseling', 'Financial counseling', 0, NEW.created_at, 1),
    (NEW.id || ':stage:procedure_booked', NEW.id, 'procedure_booked', 'Procedure booked', 0, NEW.created_at, 1),
    (NEW.id || ':stage:admission', NEW.id, 'admission', 'Admission', 0, NEW.created_at, 1),
    (NEW.id || ':stage:treatment_completed', NEW.id, 'treatment_completed', 'Treatment completed', 0, NEW.created_at, 1),
    (NEW.id || ':stage:revenue_recorded', NEW.id, 'revenue_recorded', 'Revenue recorded', 0, NEW.created_at, 1),
    (NEW.id || ':stage:closed', NEW.id, 'closed', 'Closed', 1, NEW.created_at, 1);
  INSERT OR IGNORE INTO crm_allowed_transitions (id, tenant_id, from_stage_id, to_stage_id, policy_json, created_at, version) VALUES
    (NEW.id || ':transition:received:source_identified', NEW.id, NEW.id || ':stage:received', NEW.id || ':stage:source_identified', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:received:assigned', NEW.id, NEW.id || ':stage:received', NEW.id || ':stage:assigned', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:received:closed', NEW.id, NEW.id || ':stage:received', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:source_identified:assigned', NEW.id, NEW.id || ':stage:source_identified', NEW.id || ':stage:assigned', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:source_identified:closed', NEW.id, NEW.id || ':stage:source_identified', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:assigned:contact_attempted', NEW.id, NEW.id || ':stage:assigned', NEW.id || ':stage:contact_attempted', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:assigned:closed', NEW.id, NEW.id || ':stage:assigned', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:contact_attempted:contact_attempted', NEW.id, NEW.id || ':stage:contact_attempted', NEW.id || ':stage:contact_attempted', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:contact_attempted:meaningful_connection', NEW.id, NEW.id || ':stage:contact_attempted', NEW.id || ':stage:meaningful_connection', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:contact_attempted:follow_up_active', NEW.id, NEW.id || ':stage:contact_attempted', NEW.id || ':stage:follow_up_active', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:contact_attempted:closed', NEW.id, NEW.id || ':stage:contact_attempted', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:meaningful_connection:requirement_identified', NEW.id, NEW.id || ':stage:meaningful_connection', NEW.id || ':stage:requirement_identified', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:meaningful_connection:follow_up_active', NEW.id, NEW.id || ':stage:meaningful_connection', NEW.id || ':stage:follow_up_active', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:meaningful_connection:closed', NEW.id, NEW.id || ':stage:meaningful_connection', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:requirement_identified:qualified', NEW.id, NEW.id || ':stage:requirement_identified', NEW.id || ':stage:qualified', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:requirement_identified:follow_up_active', NEW.id, NEW.id || ':stage:requirement_identified', NEW.id || ':stage:follow_up_active', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:requirement_identified:closed', NEW.id, NEW.id || ':stage:requirement_identified', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:qualified:follow_up_active', NEW.id, NEW.id || ':stage:qualified', NEW.id || ':stage:follow_up_active', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:qualified:appointment_suggested', NEW.id, NEW.id || ':stage:qualified', NEW.id || ':stage:appointment_suggested', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:qualified:closed', NEW.id, NEW.id || ':stage:qualified', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:follow_up_active:contact_attempted', NEW.id, NEW.id || ':stage:follow_up_active', NEW.id || ':stage:contact_attempted', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:follow_up_active:meaningful_connection', NEW.id, NEW.id || ':stage:follow_up_active', NEW.id || ':stage:meaningful_connection', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:follow_up_active:appointment_suggested', NEW.id, NEW.id || ':stage:follow_up_active', NEW.id || ':stage:appointment_suggested', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:follow_up_active:closed', NEW.id, NEW.id || ':stage:follow_up_active', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:appointment_suggested:appointment_booked', NEW.id, NEW.id || ':stage:appointment_suggested', NEW.id || ':stage:appointment_booked', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:appointment_suggested:follow_up_active', NEW.id, NEW.id || ':stage:appointment_suggested', NEW.id || ':stage:follow_up_active', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:appointment_suggested:closed', NEW.id, NEW.id || ':stage:appointment_suggested', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:appointment_booked:appointment_confirmed', NEW.id, NEW.id || ':stage:appointment_booked', NEW.id || ':stage:appointment_confirmed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:appointment_booked:follow_up_active', NEW.id, NEW.id || ':stage:appointment_booked', NEW.id || ':stage:follow_up_active', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:appointment_booked:closed', NEW.id, NEW.id || ':stage:appointment_booked', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:appointment_confirmed:arrived', NEW.id, NEW.id || ':stage:appointment_confirmed', NEW.id || ':stage:arrived', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:appointment_confirmed:follow_up_active', NEW.id, NEW.id || ':stage:appointment_confirmed', NEW.id || ':stage:follow_up_active', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:appointment_confirmed:closed', NEW.id, NEW.id || ':stage:appointment_confirmed', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:arrived:consultation', NEW.id, NEW.id || ':stage:arrived', NEW.id || ':stage:consultation', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:arrived:closed', NEW.id, NEW.id || ':stage:arrived', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:consultation:treatment_advised', NEW.id, NEW.id || ':stage:consultation', NEW.id || ':stage:treatment_advised', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:consultation:financial_counseling', NEW.id, NEW.id || ':stage:consultation', NEW.id || ':stage:financial_counseling', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:consultation:closed', NEW.id, NEW.id || ':stage:consultation', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:treatment_advised:financial_counseling', NEW.id, NEW.id || ':stage:treatment_advised', NEW.id || ':stage:financial_counseling', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:treatment_advised:procedure_booked', NEW.id, NEW.id || ':stage:treatment_advised', NEW.id || ':stage:procedure_booked', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:treatment_advised:treatment_completed', NEW.id, NEW.id || ':stage:treatment_advised', NEW.id || ':stage:treatment_completed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:treatment_advised:closed', NEW.id, NEW.id || ':stage:treatment_advised', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:financial_counseling:procedure_booked', NEW.id, NEW.id || ':stage:financial_counseling', NEW.id || ':stage:procedure_booked', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:financial_counseling:treatment_completed', NEW.id, NEW.id || ':stage:financial_counseling', NEW.id || ':stage:treatment_completed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:financial_counseling:closed', NEW.id, NEW.id || ':stage:financial_counseling', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:procedure_booked:admission', NEW.id, NEW.id || ':stage:procedure_booked', NEW.id || ':stage:admission', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:procedure_booked:treatment_completed', NEW.id, NEW.id || ':stage:procedure_booked', NEW.id || ':stage:treatment_completed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:procedure_booked:closed', NEW.id, NEW.id || ':stage:procedure_booked', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:admission:treatment_completed', NEW.id, NEW.id || ':stage:admission', NEW.id || ':stage:treatment_completed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:admission:revenue_recorded', NEW.id, NEW.id || ':stage:admission', NEW.id || ':stage:revenue_recorded', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:admission:closed', NEW.id, NEW.id || ':stage:admission', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:treatment_completed:revenue_recorded', NEW.id, NEW.id || ':stage:treatment_completed', NEW.id || ':stage:revenue_recorded', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:treatment_completed:closed', NEW.id, NEW.id || ':stage:treatment_completed', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1),
    (NEW.id || ':transition:revenue_recorded:closed', NEW.id, NEW.id || ':stage:revenue_recorded', NEW.id || ':stage:closed', '{"active":true,"bootstrap":true}', NEW.created_at, 1);
  INSERT OR IGNORE INTO crm_lifecycle_reasons (id, tenant_id, stage_id, key, label, requires_evidence, created_at, version) VALUES
    (NEW.id || ':reason:not_interested', NEW.id, NEW.id || ':stage:closed', 'not_interested', 'Not interested', 1, NEW.created_at, 1),
    (NEW.id || ':reason:unreachable', NEW.id, NEW.id || ':stage:closed', 'unreachable', 'Unable to contact', 0, NEW.created_at, 1),
    (NEW.id || ':reason:invalid_contact', NEW.id, NEW.id || ':stage:closed', 'invalid_contact', 'Invalid contact', 1, NEW.created_at, 1),
    (NEW.id || ':reason:clinically_ineligible', NEW.id, NEW.id || ':stage:closed', 'clinically_ineligible', 'Clinically ineligible', 1, NEW.created_at, 1),
    (NEW.id || ':reason:financial', NEW.id, NEW.id || ':stage:closed', 'financial', 'Financial constraint', 1, NEW.created_at, 1),
    (NEW.id || ':reason:competition', NEW.id, NEW.id || ':stage:closed', 'competition', 'Competing provider', 1, NEW.created_at, 1),
    (NEW.id || ':reason:already_treated', NEW.id, NEW.id || ':stage:closed', 'already_treated', 'Already treated', 1, NEW.created_at, 1),
    (NEW.id || ':reason:closed_other', NEW.id, NEW.id || ':stage:closed', 'closed_other', 'Other documented reason', 1, NEW.created_at, 1);
END;
