import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { auditColumns, tenantColumns } from "./common";

export const tenants = sqliteTable("crm_tenants", {
  id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(),
  timezone: text("timezone").notNull().default("Asia/Kolkata"), status: text("status").notNull().default("active"), ...auditColumns(),
}, (t) => [uniqueIndex("crm_tenants_slug_uq").on(t.slug)]);
export const branches = sqliteTable("crm_branches", { id: text("id").primaryKey(), ...tenantColumns(), name: text("name").notNull(), timezone: text("timezone").notNull(), status: text("status").notNull().default("active") }, (t) => [uniqueIndex("crm_branches_tenant_id_uq").on(t.tenantId, t.id), index("crm_branches_tenant_idx").on(t.tenantId)]);
export const teams = sqliteTable("crm_teams", { id: text("id").primaryKey(), ...tenantColumns(), branchId: text("branch_id"), name: text("name").notNull(), status: text("status").notNull().default("active") }, (t) => [uniqueIndex("crm_teams_tenant_id_uq").on(t.tenantId, t.id), index("crm_teams_tenant_branch_idx").on(t.tenantId, t.branchId)]);
export const crmUsers = sqliteTable("crm_users", { id: text("id").primaryKey(), displayName: text("display_name").notNull(), emailCiphertext: text("email_ciphertext"), status: text("status").notNull().default("active"), ...auditColumns() });
export const oidcIdentities = sqliteTable("crm_oidc_identities", { id: text("id").primaryKey(), userId: text("user_id").notNull(), issuer: text("issuer").notNull(), subject: text("subject").notNull(), claimsVersion: integer("claims_version").notNull().default(1), ...auditColumns() }, (t) => [uniqueIndex("crm_oidc_issuer_subject_uq").on(t.issuer, t.subject), index("crm_oidc_user_idx").on(t.userId)]);
export const roles = sqliteTable("crm_roles", { id: text("id").primaryKey(), ...tenantColumns(), key: text("key").notNull(), name: text("name").notNull(), system: integer("system", { mode: "boolean" }).notNull().default(false) }, (t) => [uniqueIndex("crm_roles_tenant_key_uq").on(t.tenantId, t.key)]);
export const rolePermissions = sqliteTable("crm_role_permissions", { id: text("id").primaryKey(), ...tenantColumns(), roleId: text("role_id").notNull(), permission: text("permission").notNull() }, (t) => [uniqueIndex("crm_role_permissions_uq").on(t.tenantId, t.roleId, t.permission)]);
export const memberships = sqliteTable("crm_memberships", { id: text("id").primaryKey(), ...tenantColumns(), userId: text("user_id").notNull(), roleId: text("role_id").notNull(), branchId: text("branch_id"), teamId: text("team_id"), status: text("status").notNull().default("active") }, (t) => [uniqueIndex("crm_memberships_tenant_id_uq").on(t.tenantId, t.id), uniqueIndex("crm_memberships_user_tenant_uq").on(t.userId, t.tenantId), index("crm_memberships_scope_idx").on(t.tenantId, t.branchId, t.teamId)]);
export const invitations = sqliteTable("crm_invitations", { id: text("id").primaryKey(), ...tenantColumns(), emailCiphertext: text("email_ciphertext").notNull(), roleId: text("role_id").notNull(), tokenHash: text("token_hash").notNull(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(), acceptedAt: integer("accepted_at", { mode: "timestamp_ms" }) }, (t) => [uniqueIndex("crm_invitations_token_uq").on(t.tokenHash)]);
export const sessions = sqliteTable("crm_sessions", { id: text("id").primaryKey(), ...tenantColumns(), membershipId: text("membership_id").notNull(), tokenHash: text("token_hash").notNull(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(), revokedAt: integer("revoked_at", { mode: "timestamp_ms" }) }, (t) => [uniqueIndex("crm_sessions_token_uq").on(t.tokenHash), index("crm_sessions_membership_idx").on(t.tenantId, t.membershipId)]);
export const servicePrincipals = sqliteTable("crm_service_principals", { id: text("id").primaryKey(), ...tenantColumns(), name: text("name").notNull(), credentialHash: text("credential_hash").notNull(), scopesJson: text("scopes_json").notNull(), disabledAt: integer("disabled_at", { mode: "timestamp_ms" }) }, (t) => [uniqueIndex("crm_service_principal_credential_uq").on(t.credentialHash)]);
