import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { tenantColumns } from "./common";
export const idempotencyCommands = sqliteTable("crm_idempotency_commands", { id: text("id").primaryKey(), ...tenantColumns(), actorKey: text("actor_key").notNull(), operation: text("operation").notNull(), idempotencyKey: text("idempotency_key").notNull(), requestHash: text("request_hash").notNull(), resultCiphertext: text("result_ciphertext"), status: text("status").notNull(), expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("crm_idempotency_uq").on(t.tenantId, t.actorKey, t.operation, t.idempotencyKey), index("crm_idempotency_expiry_idx").on(t.tenantId, t.status, t.expiresAt)]);
export const webhookInbox = sqliteTable("crm_webhook_inbox", { id: text("id").primaryKey(), ...tenantColumns(), provider: text("provider").notNull(), integrationId: text("integration_id").notNull(), providerEventId: text("provider_event_id").notNull(), payloadCiphertext: text("payload_ciphertext").notNull(), receivedAt: integer("received_at", { mode: "timestamp_ms" }).notNull(), attemptCount: integer("attempt_count").notNull().default(0), nextAttemptAt: integer("next_attempt_at", { mode: "timestamp_ms" }), status: text("status").notNull().default("received") }, (t) => [uniqueIndex("crm_inbox_event_uq").on(t.provider, t.integrationId, t.providerEventId), index("crm_inbox_status_idx").on(t.tenantId, t.status, t.nextAttemptAt, t.receivedAt)]);
export const transactionalOutbox = sqliteTable("crm_transactional_outbox", { id: text("id").primaryKey(), ...tenantColumns(), operationKey: text("operation_key").notNull(), type: text("type").notNull(), payloadCiphertext: text("payload_ciphertext").notNull(), status: text("status").notNull().default("pending"), availableAt: integer("available_at", { mode: "timestamp_ms" }).notNull(), attemptCount: integer("attempt_count").notNull().default(0), nextAttemptAt: integer("next_attempt_at", { mode: "timestamp_ms" }), publishedAt: integer("published_at", { mode: "timestamp_ms" }) }, (t) => [uniqueIndex("crm_outbox_operation_uq").on(t.tenantId, t.operationKey), index("crm_outbox_pending_idx").on(t.tenantId, t.status, t.nextAttemptAt, t.availableAt)]);
export const durableJobs = sqliteTable("crm_durable_jobs", { id: text("id").primaryKey(), ...tenantColumns(), type: text("type").notNull(), payloadCiphertext: text("payload_ciphertext").notNull(), dueAt: integer("due_at", { mode: "timestamp_ms" }).notNull(), state: text("state").notNull().default("pending"), leaseOwner: text("lease_owner"), leaseExpiresAt: integer("lease_expires_at", { mode: "timestamp_ms" }), attempts: integer("attempts").notNull().default(0) }, (t) => [index("crm_jobs_due_idx").on(t.tenantId, t.state, t.dueAt)]);
export const deadLetters = sqliteTable("crm_dead_letters", { id: text("id").primaryKey(), ...tenantColumns(), jobId: text("job_id"), reason: text("reason").notNull(), payloadCiphertext: text("payload_ciphertext"), occurredAt: integer("occurred_at", { mode: "timestamp_ms" }).notNull() });
export const auditEvents = sqliteTable("crm_audit_events", { id: text("id").primaryKey(), ...tenantColumns(), actorKey: text("actor_key").notNull(), action: text("action").notNull(), resourceType: text("resource_type").notNull(), resourceId: text("resource_id"), requestId: text("request_id").notNull(), occurredAt: integer("occurred_at", { mode: "timestamp_ms" }).notNull(), detailCiphertext: text("detail_ciphertext") }, (t) => [index("crm_audit_resource_idx").on(t.tenantId, t.resourceType, t.resourceId, t.occurredAt)]);
export const migrationReconciliations = sqliteTable("crm_migration_reconciliations", { id: text("id").primaryKey(), environment: text("environment").notNull(), legacyShape: text("legacy_shape").notNull(), baselineVersion: text("baseline_version").notNull(), inspectedAt: integer("inspected_at", { mode: "timestamp_ms" }).notNull(), checksum: text("checksum").notNull(), notes: text("notes") }, (t) => [uniqueIndex("crm_migration_reconciliation_uq").on(t.environment, t.checksum)]);
