import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

/** Pre-tenant tables. Read/export only while the documented backfill is underway. */
export const users = sqliteTable("users", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), role: text("role").notNull().default("agent"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const leads = sqliteTable("leads", { id: text("id").primaryKey(), name: text("name").notNull(), phone: text("phone"), email: text("email"), source: text("source").notNull().default("manual"), status: text("status").notNull().default("new"), ownerId: text("owner_id"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const calls = sqliteTable("calls", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), agentId: text("agent_id").notNull(), direction: text("direction").notNull(), outcome: text("outcome").notNull().default("pending"), durationSec: integer("duration_sec").default(0), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const notes = sqliteTable("notes", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), authorId: text("author_id").notNull(), content: text("content").notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const tasks = sqliteTable("tasks", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), assigneeId: text("assignee_id").notNull(), title: text("title").notNull(), dueAt: integer("due_at", { mode: "timestamp" }).notNull(), status: text("status").notNull().default("open"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const appointments = sqliteTable("appointments", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), ownerId: text("owner_id").notNull(), startsAt: integer("starts_at", { mode: "timestamp" }).notNull(), mode: text("mode").notNull().default("online"), status: text("status").notNull().default("booked"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const reviews = sqliteTable("reviews", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), callId: text("call_id"), confidence: integer("confidence").default(85), suggestedTemperature: text("suggested_temperature").default("Hot"), suggestedObjection: text("suggested_objection"), summaryText: text("summary_text").notNull(), structuredRemark: text("structured_remark"), status: text("status").notNull().default("draft"), reviewedBy: text("reviewed_by"), reviewedAt: integer("reviewed_at", { mode: "timestamp" }), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const messages = sqliteTable("messages", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), channel: text("channel").notNull().default("whatsapp"), direction: text("direction").notNull().default("outbound"), content: text("content").notNull(), status: text("status").notNull().default("sent"), sentBy: text("sent_by"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const auditLogs = sqliteTable("audit_logs", { id: text("id").primaryKey(), actorId: text("actor_id").notNull(), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), details: text("details"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
