import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

/** Pre-tenant tables. Read/export only while the documented backfill is underway. */
export const users = sqliteTable("users", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), role: text("role").notNull().default("agent"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const leads = sqliteTable("leads", { id: text("id").primaryKey(), name: text("name").notNull(), phone: text("phone"), email: text("email"), source: text("source").notNull().default("manual"), status: text("status").notNull().default("new"), ownerId: text("owner_id"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const calls = sqliteTable("calls", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), agentId: text("agent_id").notNull(), direction: text("direction").notNull(), outcome: text("outcome").notNull().default("pending"), durationSec: integer("duration_sec").default(0), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const notes = sqliteTable("notes", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), authorId: text("author_id").notNull(), content: text("content").notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const tasks = sqliteTable("tasks", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), assigneeId: text("assignee_id").notNull(), title: text("title").notNull(), dueAt: integer("due_at", { mode: "timestamp" }).notNull(), status: text("status").notNull().default("open"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const appointments = sqliteTable("appointments", { id: text("id").primaryKey(), leadId: text("lead_id").notNull(), ownerId: text("owner_id").notNull(), startsAt: integer("starts_at", { mode: "timestamp" }).notNull(), mode: text("mode").notNull().default("online"), status: text("status").notNull().default("booked"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
