import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { tenantColumns } from "./common";
export const diseases = sqliteTable("crm_diseases", { id: text("id").primaryKey(), ...tenantColumns(), code: text("code").notNull(), name: text("name").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true) }, (t) => [uniqueIndex("crm_diseases_code_uq").on(t.tenantId, t.code)]);
export const treatments = sqliteTable("crm_treatments", { id: text("id").primaryKey(), ...tenantColumns(), diseaseId: text("disease_id"), code: text("code").notNull(), name: text("name").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true) }, (t) => [uniqueIndex("crm_treatments_code_uq").on(t.tenantId, t.code)]);
export const questionnaires = sqliteTable("crm_questionnaires", { id: text("id").primaryKey(), ...tenantColumns(), key: text("key").notNull(), versionLabel: text("version_label").notNull(), definitionJson: text("definition_json").notNull(), effectiveAt: integer("effective_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("crm_questionnaires_version_uq").on(t.tenantId, t.key, t.versionLabel)]);
export const scorePolicies = sqliteTable("crm_score_policies", { id: text("id").primaryKey(), ...tenantColumns(), key: text("key").notNull(), versionLabel: text("version_label").notNull(), rulesJson: text("rules_json").notNull(), effectiveAt: integer("effective_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("crm_score_policy_version_uq").on(t.tenantId, t.key, t.versionLabel)]);
export const qualificationAnswers = sqliteTable("crm_qualification_answers", { id: text("id").primaryKey(), ...tenantColumns(), leadId: text("lead_id").notNull(), questionnaireId: text("questionnaire_id").notNull(), questionKey: text("question_key").notNull(), answerCiphertext: text("answer_ciphertext"), answeredAt: integer("answered_at", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("crm_answer_uq").on(t.tenantId, t.leadId, t.questionnaireId, t.questionKey), index("crm_answers_lead_idx").on(t.tenantId, t.leadId)]);
export const qualificationScores = sqliteTable("crm_qualification_scores", { id: text("id").primaryKey(), ...tenantColumns(), leadId: text("lead_id").notNull(), policyId: text("policy_id").notNull(), classification: text("classification").notNull(), total: integer("total").notNull(), evidenceJson: text("evidence_json").notNull(), assessedAt: integer("assessed_at", { mode: "timestamp_ms" }).notNull(), reviewedByMembershipId: text("reviewed_by_membership_id"), overrideReason: text("override_reason") }, (t) => [index("crm_scores_lead_idx").on(t.tenantId, t.leadId, t.assessedAt)]);
export const scoreComponents = sqliteTable("crm_score_components", { id: text("id").primaryKey(), ...tenantColumns(), scoreId: text("score_id").notNull(), component: text("component").notNull(), points: integer("points").notNull(), evidenceJson: text("evidence_json") }, (t) => [uniqueIndex("crm_score_component_uq").on(t.tenantId, t.scoreId, t.component)]);
